version: '3'
services:
  php:
    build: .
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - greenavi-net

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    command: uvicorn fastapi_app.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./:/app
    ports:
      - "8001:8001"
    networks:
      - greenavi-net

networks:
  greenavi-net:
